version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"

  pre_build:
    commands:
      - echo "Pre-build phase"
      - cd 02-codebuild
      - pwd
      - ls -la

  build:
    commands:
      - echo "Build phase"
      - grep "AWS CodeBuild works!" index.html

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  base-directory: 02-codebuild
  files:
    - index.html
